# Zabbix particulars
protocol: "http"
host: "localhost"
port: 80
username: ""
password: ""
jsonRpcPath: "api_jsonrpc.php"

#Include Exclude Hosts. Include takes precedence over exclude.
includeHosts: []
excludeHosts: []

#Provide either includeItems or excludeItems
#Only matched items will be included from the hosts after applying includeHosts/excludeHosts
includeItems: []

#Matched items will be excluded from the hosts after applying includeHosts/excludeHosts
excludeItems: []

#Replaces characters in metric name with the specified characters.
# "replace" takes any regular expression
# "replaceWith" takes the string to replace the matched characters
metricCharacterReplacer:
   - replace: ","
     replaceWith: ";"

#This will create this metric in all the tiers, under this path
#metricPathPrefix: Custom Metrics|Zabbix|

#This will create it in specific Tier/Component. Make sure to replace <COMPONENT_ID> with the appropriate one from your environment.
#To find the <COMPONENT_ID> in your environment, please follow the screenshot https://docs.appdynamics.com/display/PRO42/Build+a+Monitoring+Extension+Using+Java
metricPathPrefix: Server|Component:<COMPONENT_ID>|Custom Metrics|Zabbix|
